"""
DIMACS-style graph format reader/writer.

Supports the common DIMACS max-flow and min-cost flow challenge formats
for interoperability with standard benchmark instances.
"""

from __future__ import annotations

import re
from .graph import FlowNetwork


def read_dimacs(path: str) -> tuple[FlowNetwork, int, int]:
    """Read a DIMACS-format max-flow or min-cost flow problem.

    Format (simplified):
      c <comment>
      p max <nodes> <edges>
      n <node> s    (source)
      n <node> t    (sink)
      a <from> <to> <capacity> [<cost>]

    Returns (network, source, sink).
    """
    n_nodes = 0
    source = -1
    sink = -1
    edges = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line[0] == "c":
                continue
            parts = line.split()
            tag = parts[0]
            if tag == "p":
                # p max N E  or  p min N E
                n_nodes = int(parts[2])
            elif tag == "n":
                node = int(parts[1]) - 1  # 1-indexed → 0-indexed
                if parts[2] == "s":
                    source = node
                elif parts[2] == "t":
                    sink = node
            elif tag == "a":
                u = int(parts[1]) - 1
                v = int(parts[2]) - 1
                cap = float(parts[3])
                cost = float(parts[4]) if len(parts) > 4 else 0.0
                edges.append((u, v, cap, cost))
    if n_nodes == 0:
        raise ValueError("No 'p' line found in DIMACS file")
    if source < 0 or sink < 0:
        raise ValueError("Source/sink not specified in DIMACS file")
    net = FlowNetwork(n_nodes)
    for u, v, cap, cost in edges:
        net.add_edge(u, v, cap, cost)
    return net, source, sink


def write_dimacs(net: FlowNetwork, source: int, sink: int, path: str) -> None:
    """Write a FlowNetwork in DIMACS max-flow format."""
    with open(path, "w") as f:
        f.write(f"c Generated by network-flow-solver\n")
        f.write(f"p max {net.n} {net.edge_count()}\n")
        f.write(f"n {source + 1} s\n")
        f.write(f"n {sink + 1} t\n")
        for u in range(net.n):
            for e in net.graph[u]:
                if e.cap > 0:
                    cost_str = f" {e.cost}" if e.cost != 0 else ""
                    f.write(f"a {u + 1} {e.to + 1} {e.cap}{cost_str}\n")


def read_dimacs_min_cost(path: str) -> tuple[FlowNetwork, int, int]:
    """Read a DIMACS min-cost flow format (same as max-flow but with costs)."""
    return read_dimacs(path)