"""
Additional graph I/O formats.

Supports reading and writing flow networks in multiple formats:
  - GraphML (XML-based, interoperable with NetworkX, Gephi, etc.)
  - Edge list (plain text: ``u v capacity [cost]`` per line)
  - Adjacency matrix (CSV / TSV)
  - LEMON graph format (LGF-style)

All parsers return (FlowNetwork, source, sink) tuples where applicable.
"""

from __future__ import annotations

import csv
import io
import xml.etree.ElementTree as ET
from pathlib import Path

from .graph import FlowNetwork


def read_edge_list(path: str,
                   source: int = 0,
                   sink: int = -1,
                   has_header: bool = False,
                   delimiter: str | None = None) -> tuple[FlowNetwork, int, int]:
    """Read a flow network from a whitespace-delimited edge list.

    Each non-comment line has the form::

        u v capacity [cost]

    Lines starting with ``#`` are comments.  The number of nodes is inferred
    from the maximum node id + 1.

    Parameters
    ----------
    path : str
        Path to the edge list file.
    source : int
        Source node index (default 0).
    sink : int
        Sink node index.  If -1, set to max node id.
    has_header : bool
        If True, skip the first line.

    Returns
    -------
    (FlowNetwork, source, sink)
    """
    edges: list[tuple[int, int, float, float]] = []
    max_node = -1
    with open(path) as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if has_header and i == 0:
                continue
            parts = line.split(delimiter) if delimiter else line.split()
            u, v = int(parts[0]), int(parts[1])
            cap = float(parts[2])
            cost = float(parts[3]) if len(parts) > 3 else 0.0
            edges.append((u, v, cap, cost))
            max_node = max(max_node, u, v)

    n = max_node + 1
    if sink < 0:
        sink = max_node
    net = FlowNetwork(n)
    for u, v, cap, cost in edges:
        net.add_edge(u, v, cap, cost)
    return net, source, sink


def write_edge_list(net: FlowNetwork, path: str) -> None:
    """Write network as an edge list file."""
    with open(path, "w") as f:
        f.write(f"# Generated by network-flow-solver\n")
        f.write(f"# format: from to capacity [cost]\n")
        f.write(f"# nodes: {net.n}\n")
        for u in range(net.n):
            for e in net.graph[u]:
                if e.cap > 0:
                    cost_str = f"  {e.cost}" if e.cost != 0 else ""
                    f.write(f"{u} {e.to} {e.cap}{cost_str}\n")


def read_adjacency_matrix(path: str,
                          source: int = 0,
                          sink: int = -1,
                          delimiter: str = ",") -> tuple[FlowNetwork, int, int]:
    """Read a flow network from a CSV/TSV adjacency matrix.

    The matrix is N×N where ``matrix[i][j]`` is the capacity of edge i→j.
    A zero or empty entry means no edge.

    Parameters
    ----------
    path : str
        Path to the CSV/TSV file.
    source : int
        Source node (default 0).
    sink : int
        Sink node.  If -1, defaults to N-1.
    delimiter : str
        Field delimiter (default comma).

    Returns
    -------
    (FlowNetwork, source, sink)
    """
    with open(path, newline="") as f:
        reader = csv.reader(f, delimiter=delimiter)
        rows = [[float(v) for v in row] for row in reader if row]

    n = len(rows)
    if sink < 0:
        sink = n - 1
    net = FlowNetwork(n)
    for i in range(n):
        for j in range(len(rows[i])):
            if rows[i][j] > 0:
                net.add_edge(i, j, rows[i][j])
    return net, source, sink


def write_adjacency_matrix(net: FlowNetwork, path: str,
                           delimiter: str = ",") -> None:
    """Write network as an adjacency matrix CSV."""
    n = net.n
    matrix = [[0.0] * n for _ in range(n)]
    for u in range(n):
        for e in net.graph[u]:
            if e.cap > 0:
                matrix[u][e.to] = e.cap
    with open(path, "w", newline="") as f:
        writer = csv.writer(f, delimiter=delimiter)
        for row in matrix:
            writer.writerow(row)


def read_graphml(path: str) -> tuple[FlowNetwork, int, int]:
    """Read a GraphML file and construct a FlowNetwork.

    Edge capacities are read from the ``capacity`` (or ``weight``) edge data
    key.  Source and sink are read from node attributes ``source`` and
    ``sink`` if present; otherwise default to 0 and n-1.

    Parameters
    ----------
    path : str
        Path to the GraphML file.

    Returns
    -------
    (FlowNetwork, source, sink)
    """
    tree = ET.parse(path)
    root = tree.getroot()

    # GraphML uses XML namespaces
    ns = ""
    if root.tag.startswith("{"):
        ns = root.tag.split("}")[0] + "}"

    # Parse key definitions (edge data keys)
    key_types: dict[str, str] = {}
    for key in root.findall(f"{ns}key"):
        kid = key.get("id", "")
        kfor = key.get("for", "edge")
        kname = key.get("attr.name", kid)
        key_types[kid] = kname

    # Parse nodes
    graph = root.find(f"{ns}graph")
    if graph is None:
        raise ValueError("No <graph> element in GraphML file")

    node_ids: list[str] = []
    node_idx: dict[str, int] = {}
    source = -1
    sink = -1

    for node in graph.findall(f"{ns}node"):
        nid = node.get("id", str(len(node_ids)))
        idx = len(node_ids)
        node_ids.append(nid)
        node_idx[nid] = idx

        # Check for source/sink data
        for data in node.findall(f"{ns}data"):
            key = data.get("key", "")
            val = (data.text or "").strip()
            if key in ("source", "is_source") and val in ("true", "1"):
                source = idx
            elif key in ("sink", "is_sink") and val in ("true", "1"):
                sink = idx

    n = len(node_ids)

    # Parse edges
    edges: list[tuple[int, int, float, float]] = []
    for edge in graph.findall(f"{ns}edge"):
        src = edge.get("source", "")
        tgt = edge.get("target", "")
        if src not in node_idx or tgt not in node_idx:
            continue
        u = node_idx[src]
        v = node_idx[tgt]
        cap = 1.0
        cost = 0.0
        for data in edge.findall(f"{ns}data"):
            key = data.get("key", "")
            kname = key_types.get(key, key)
            val = (data.text or "1").strip()
            if kname in ("capacity", "cap", "weight"):
                cap = float(val)
            elif kname in ("cost", "c"):
                cost = float(val)
        edges.append((u, v, cap, cost))

    if source < 0:
        source = 0
    if sink < 0:
        sink = n - 1

    net = FlowNetwork(n)
    for u, v, cap, cost in edges:
        if cap > 0 and u != v:
            net.add_edge(u, v, cap, cost)
    return net, source, sink


def write_graphml(net: FlowNetwork, path: str,
                  source: int | None = None,
                  sink: int | None = None) -> None:
    """Write a FlowNetwork in GraphML format."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
        '  <key id="capacity" for="edge" attr.name="capacity" attr.type="double"/>',
        '  <key id="cost" for="edge" attr.name="cost" attr.type="double"/>',
        '  <key id="source" for="node" attr.name="source" attr.type="boolean"/>',
        '  <key id="sink" for="node" attr.name="sink" attr.type="boolean"/>',
        f'  <graph edgedefault="directed">',
    ]
    for i in range(net.n):
        attrs = ""
        if i == source:
            attrs = '<data key="source">true</data>'
        elif i == sink:
            attrs = '<data key="sink">true</data>'
        lines.append(f'    <node id="n{i}">{attrs}</node>')

    edge_id = 0
    for u in range(net.n):
        for e in net.graph[u]:
            if e.cap > 0:
                cost_str = f'<data key="cost">{e.cost}</data>' if e.cost != 0 else ""
                lines.append(
                    f'    <edge id="e{edge_id}" source="n{u}" target="n{e.to}">'
                    f'<data key="capacity">{e.cap}</data>{cost_str}</edge>'
                )
                edge_id += 1

    lines.append('  </graph>')
    lines.append('</graphml>')
    Path(path).write_text("\n".join(lines) + "\n")


def read_lgf(path: str) -> tuple[FlowNetwork, int, int]:
    """Read a LEMON Graph Format (LGF) file.

    A simplified parser for LGF format with sections ``@nodes`` and
    ``@edges`` (or ``@arcs``).  Node labels ``source`` and ``sink`` mark
    terminals.  Edge columns: ``u v capacity [cost]``.

    Returns
    -------
    (FlowNetwork, source, sink)
    """
    source = -1
    sink = -1
    node_map: dict[int, int] = {}  # original label → internal index
    edges: list[tuple[int, int, float, float]] = []
    section = None

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith("@"):
                section = line[1:].split()[0]
                continue
            if section == "nodes":
                parts = line.split()
                label = int(parts[0])
                idx = len(node_map)
                node_map[label] = idx
                if len(parts) > 1:
                    if parts[1] == "source":
                        source = idx
                    elif parts[1] == "sink":
                        sink = idx
            elif section in ("edges", "arcs"):
                parts = line.split()
                u = node_map.get(int(parts[0]), -1)
                v = node_map.get(int(parts[1]), -1)
                cap = float(parts[2]) if len(parts) > 2 else 1.0
                cost = float(parts[3]) if len(parts) > 3 else 0.0
                if u >= 0 and v >= 0:
                    edges.append((u, v, cap, cost))

    n = len(node_map)
    if source < 0:
        source = 0
    if sink < 0:
        sink = n - 1
    net = FlowNetwork(n)
    for u, v, cap, cost in edges:
        net.add_edge(u, v, cap, cost)
    return net, source, sink