"""Mesh export to common 3-D file formats (pure stdlib)."""

from __future__ import annotations

import math
import struct
from typing import List, Sequence, Tuple

from .mesh import Mesh


def write_obj(mesh: Mesh, path: str) -> None:
    """Write a Wavefront .obj file (vertices, faces, vertex normals)."""
    with open(path, "w") as fh:
        fh.write("# Generated by mcengine\n")
        for v in mesh.vertices:
            fh.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        if mesh.normals:
            for n in mesh.normals:
                fh.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
            for (a, b, c) in mesh.faces:
                fh.write(f"f {a+1}//{a+1} {b+1}//{b+1} {c+1}//{c+1}\n")
        else:
            for (a, b, c) in mesh.faces:
                fh.write(f"f {a+1} {b+1} {c+1}\n")


def write_off(mesh: Mesh, path: str) -> None:
    """Write a simple OFF file."""
    with open(path, "w") as fh:
        fh.write("OFF\n")
        fh.write(f"{mesh.num_vertices} {mesh.num_faces} 0\n")
        for v in mesh.vertices:
            fh.write(f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for (a, b, c) in mesh.faces:
            fh.write(f"3 {a} {b} {c}\n")


def write_ply_ascii(mesh: Mesh, path: str, normals: bool = True) -> None:
    """Write an ASCII PLY file with vertices + faces (and normals if present)."""
    has_normals = normals and bool(mesh.normals)
    props = ["property float x", "property float y", "property float z"]
    if has_normals:
        props += ["property float nx", "property float ny", "property float nz"]
    with open(path, "w") as fh:
        fh.write("ply\nformat ascii 1.0\nelement vertex %d\n" % mesh.num_vertices)
        for p in props:
            fh.write(p + "\n")
        fh.write("element face %d\n" % mesh.num_faces)
        fh.write("property list uchar int vertex_indices\nend_header\n")
        for idx, v in enumerate(mesh.vertices):
            line = f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}"
            if has_normals:
                n = mesh.normals[idx]
                line += f" {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}"
            fh.write(line + "\n")
        for (a, b, c) in mesh.faces:
            fh.write(f"3 {a} {b} {c}\n")


def write_ply_binary(mesh: Mesh, path: str, normals: bool = True) -> None:
    """Write a binary little-endian PLY (vertices + faces)."""
    has_normals = normals and bool(mesh.normals)
    with open(path, "wb") as fh:
        header = ["ply", "format binary_little_endian 1.0",
                  f"element vertex {mesh.num_vertices}",
                  "property float x", "property float y", "property float z"]
        if has_normals:
            header += ["property float nx", "property float ny", "property float nz"]
        header += [f"element face {mesh.num_faces}",
                   "property list uchar int vertex_indices", "end_header"]
        fh.write(("\n".join(header) + "\n").encode("ascii"))
        for idx, v in enumerate(mesh.vertices):
            fh.write(struct.pack("<fff", v[0], v[1], v[2]))
            if has_normals:
                n = mesh.normals[idx]
                fh.write(struct.pack("<fff", n[0], n[1], n[2]))
        for (a, b, c) in mesh.faces:
            fh.write(struct.pack("<B", 3))
            fh.write(struct.pack("<iii", a, b, c))


def write_stl_ascii(mesh: Mesh, path: str) -> None:
    """Write an ASCII STL file (per-face normals)."""
    with open(path, "w") as fh:
        fh.write("solid mcengine_mesh\n")
        for (a, b, c) in mesh.faces:
            va = mesh.vertices[a]; vb = mesh.vertices[b]; vc = mesh.vertices[c]
            n = _face_normal(va, vb, vc)
            fh.write("  facet normal %.6f %.6f %.6f\n" % n)
            fh.write("    outer loop\n")
            fh.write("      vertex %.6f %.6f %.6f\n" % va)
            fh.write("      vertex %.6f %.6f %.6f\n" % vb)
            fh.write("      vertex %.6f %.6f %.6f\n" % vc)
            fh.write("    endloop\n  endfacet\n")
        fh.write("endsolid mcengine_mesh\n")


def write_stl_binary(mesh: Mesh, path: str) -> None:
    """Write a binary STL file (80-byte header, per-face normal + 3 verts)."""
    with open(path, "wb") as fh:
        fh.write(b"mcengine binary STL\x00" + b"\x00" * 60)  # 80-byte header (20 + 60 = 80)
        fh.write(struct.pack("<I", mesh.num_faces))
        for (a, b, c) in mesh.faces:
            va = mesh.vertices[a]; vb = mesh.vertices[b]; vc = mesh.vertices[c]
            n = _face_normal(va, vb, vc)
            fh.write(struct.pack("<fff", n[0], n[1], n[2]))
            fh.write(struct.pack("<fff", va[0], va[1], va[2]))
            fh.write(struct.pack("<fff", vb[0], vb[1], vb[2]))
            fh.write(struct.pack("<fff", vc[0], vc[1], vc[2]))
            fh.write(struct.pack("<H", 0))  # attribute byte count


def write_gltf_minimal(mesh: Mesh, path: str) -> None:
    """Write a minimal glTF 2.0 file (embedded, non-indexed triangles).

    This is a tiny but valid glTF with a single mesh primitive of POSITION
    attribute.  No normals, materials, or animations — just the geometry.
    """
    import json
    import base64

    # Flatten vertices and faces into a non-indexed buffer (3 verts per face).
    floats: List[float] = []
    for (a, b, c) in mesh.faces:
        for vi in (a, b, c):
            v = mesh.vertices[vi]
            floats.extend(v)
    bdata = struct.pack("<%df" % len(floats), *floats)
    b64 = base64.b64encode(bdata).decode("ascii")
    uri = "data:application/octet-stream;base64," + b64
    gltf = {
        "asset": {"version": "2.0", "generator": "mcengine"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0}],
        "meshes": [{"primitives": [{
            "attributes": {"POSITION": 0},
            "mode": 4,  # TRIANGLES
        }]}],
        "buffers": [{"uri": uri, "byteLength": len(bdata)}],
        "bufferViews": [{"buffer": 0, "byteOffset": 0,
                         "byteLength": len(bdata), "target": 34962}],
        "accessors": [{
            "bufferView": 0, "componentType": 5126, "count": len(floats) // 3,
            "type": "VEC3",
            "min": [min(floats[i::3]) for i in range(3)],
            "max": [max(floats[i::3]) for i in range(3)],
        }],
    }
    with open(path, "w") as fh:
        json.dump(gltf, fh)


def _face_normal(a, b, c) -> Tuple[float, float, float]:
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    L = math.sqrt(nx * nx + ny * ny + nz * nz)
    if L < 1e-18:
        return (0.0, 0.0, 0.0)
    return (nx / L, ny / L, nz / L)