"""Tests for mesh export and import (round-trip)."""

import os
import struct
import pytest

from mcengine import (
    MarchingCubes, SphereSampler, analyze_mesh,
    write_obj, write_off, write_ply_ascii, write_ply_binary,
    write_stl_ascii, write_stl_binary, write_gltf_minimal,
    read_obj, read_off, read_ply_ascii, read_stl_ascii, read_stl_binary,
    read_mesh,
)
from tests.conftest import temp_file, cleanup, assert_mesh_valid


@pytest.fixture
def sphere_mesh():
    mc = MarchingCubes(SphereSampler(1.0), resolution=(16, 16, 16))
    return mc.run()


class TestOBJ:
    def test_write_read_roundtrip(self, sphere_mesh):
        path = temp_file(".obj")
        try:
            write_obj(sphere_mesh, path)
            assert os.path.exists(path)
            loaded = read_obj(path)
            assert loaded.num_vertices == sphere_mesh.num_vertices
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)

    def test_file_contents(self, sphere_mesh):
        path = temp_file(".obj")
        try:
            write_obj(sphere_mesh, path)
            with open(path) as f:
                content = f.read()
            assert content.startswith("# Generated by mcengine")
            assert "v " in content
            assert "f " in content
        finally:
            cleanup(path)


class TestOFF:
    def test_write_read_roundtrip(self, sphere_mesh):
        path = temp_file(".off")
        try:
            write_off(sphere_mesh, path)
            loaded = read_off(path)
            assert loaded.num_vertices == sphere_mesh.num_vertices
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)


class TestPLY:
    def test_ascii_roundtrip(self, sphere_mesh):
        path = temp_file(".ply")
        try:
            write_ply_ascii(sphere_mesh, path)
            loaded = read_ply_ascii(path)
            assert loaded.num_vertices == sphere_mesh.num_vertices
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)

    def test_binary(self, sphere_mesh):
        path = temp_file(".ply")
        try:
            write_ply_binary(sphere_mesh, path)
            assert os.path.exists(path)
            # Check file starts with "ply"
            with open(path, "rb") as f:
                assert f.read(3) == b"ply"
        finally:
            cleanup(path)


class TestSTL:
    def test_ascii_roundtrip(self, sphere_mesh):
        path = temp_file(".stl")
        try:
            write_stl_ascii(sphere_mesh, path)
            loaded = read_stl_ascii(path)
            assert_mesh_valid(loaded)
        finally:
            cleanup(path)

    def test_binary_header_is_80_bytes(self, sphere_mesh):
        """Binary STL header must be exactly 80 bytes."""
        path = temp_file(".stl")
        try:
            write_stl_binary(sphere_mesh, path)
            with open(path, "rb") as f:
                header = f.read(80)
                assert len(header) == 80
                face_count = struct.unpack("<I", f.read(4))[0]
                assert face_count == sphere_mesh.num_faces
        finally:
            cleanup(path)

    def test_binary_roundtrip(self, sphere_mesh):
        path = temp_file(".stl")
        try:
            write_stl_binary(sphere_mesh, path)
            loaded = read_stl_binary(path)
            assert_mesh_valid(loaded)
            # STL doesn't share vertices, so loaded mesh may have more vertices
            # but should have same face count
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)


class TestglTF:
    def test_write_gltf(self, sphere_mesh):
        import json
        path = temp_file(".gltf")
        try:
            write_gltf_minimal(sphere_mesh, path)
            with open(path) as f:
                data = json.load(f)
            assert data["asset"]["version"] == "2.0"
            assert data["asset"]["generator"] == "mcengine"
            assert len(data["meshes"]) == 1
        finally:
            cleanup(path)


class TestReadMesh:
    def test_auto_detect_obj(self, sphere_mesh):
        path = temp_file(".obj")
        try:
            write_obj(sphere_mesh, path)
            loaded = read_mesh(path)
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)

    def test_auto_detect_off(self, sphere_mesh):
        path = temp_file(".off")
        try:
            write_off(sphere_mesh, path)
            loaded = read_mesh(path)
            assert loaded.num_faces == sphere_mesh.num_faces
        finally:
            cleanup(path)

    def test_unsupported_extension(self):
        with pytest.raises(ValueError):
            read_mesh("file.xyz")