"""Lyapunov fractal renderer.

The Lyapunov fractal is generated by iterating the logistic map
``x_{n+1} = r_n · x_n · (1 - x_n)`` where the parameter ``r_n`` alternates
between two values ``a`` and ``b`` according to a binary sequence. The
Lyapunov exponent ``λ`` is computed for each ``(a, b)`` pixel and mapped
to a colour: negative λ (stable/order) in one colour range, positive λ
(chaos) in another.
"""
from __future__ import annotations

import math
from typing import List, Tuple

from .palettes import get_palette, _clamp_byte

RGB = Tuple[int, int, int]


def _lyapunov_exponent(a: float, b: float, sequence: str, max_iter: int,
                       x0: float = 0.5) -> float:
    """Compute the Lyapunov exponent for parameters ``(a, b)``.

    ``sequence`` is a string of 'a' and 'b' characters (e.g. "AB", "ABBA").
    """
    seq_len = len(sequence)
    x = x0
    # Discard the first half (transient)
    warmup = max_iter // 2
    for i in range(warmup):
        r = a if sequence[i % seq_len] == "a" else b
        if r <= 0 or r >= 4:
            return -1.0
        x = r * x * (1 - x)

    total = 0.0
    count = 0
    for i in range(warmup, max_iter):
        r = a if sequence[i % seq_len] == "a" else b
        if r <= 0 or r >= 4:
            return -1.0
        x = r * x * (1 - x)
        if x <= 0 or x >= 1:
            return -1.0
        # d/dx [r·x·(1-x)] = r·(1-2x)
        deriv = abs(r * (1 - 2 * x))
        if deriv > 0:
            total += math.log(deriv)
            count += 1

    if count == 0:
        return -1.0
    return total / count


def render_lyapunov(a_range=(2.0, 4.0), b_range=(2.0, 4.0),
                    width: int = 400, height: int = 400,
                    sequence: str = "AB", max_iter: int = 400,
                    palette_name: str = "magma", palette_size: int = 256,
                    interior_color: RGB = (0, 0, 0)) -> Tuple[List[RGB], dict]:
    """Render a Lyapunov fractal.

    Parameters
    ----------
    a_range, b_range : tuple
        Range of the parameter space to render (a on x-axis, b on y-axis).
    width, height : int
        Output image dimensions.
    sequence : str
        Alternation sequence of 'a' and 'b' characters.
    max_iter : int
        Number of iterations per pixel (higher = more detail).
    palette_name : str
        Palette to use. Negative λ (order) maps to the lower half;
        positive λ (chaos) maps to the upper half.

    Returns
    -------
    pixels : list of RGB tuples
    stats : dict
    """
    if width <= 0 or height <= 0:
        raise ValueError("width and height must be positive")
    if not sequence:
        raise ValueError("sequence must not be empty")
    if max_iter <= 0:
        raise ValueError("max_iter must be positive")

    sequence = sequence.upper()
    for ch in sequence:
        if ch not in ("A", "B"):
            raise ValueError(f"sequence must contain only 'A' and 'B': {sequence!r}")

    palette = get_palette(palette_name, palette_size)
    a_min, a_max = a_range
    b_min, b_max = b_range
    da = (a_max - a_min) / width
    db = (b_max - b_min) / height

    pixels: List[RGB] = []
    for row in range(height):
        b = b_min + (row + 0.5) * db
        for col in range(width):
            a = a_min + (col + 0.5) * da
            lam = _lyapunov_exponent(a, b, sequence, max_iter)
            if lam < -0.9:
                pixels.append(interior_color)
                continue
            # Map λ in [-2, 2] → palette index
            # Negative (order) → lower half, positive (chaos) → upper half
            t = max(0.0, min(1.0, (lam + 2.0) / 4.0))
            idx = max(0, min(palette_size - 1, int(t * (palette_size - 1))))
            pixels.append(palette[idx])

    stats = {"width": width, "height": height, "kind": "lyapunov",
             "sequence": sequence, "max_iter": max_iter}
    return pixels, stats