// Simple arithmetic expression grammar
%start expr

expr   : expr '+' term
       | expr '-' term
       | term
       ;

term   : term '*' factor
       | term '/' factor
       | factor
       ;

factor : '(' expr ')'
       | NUMBER
       ;